### ISSUE TITLE
cctbx and pymol not playing together

### ISSUE THREAD

**Issue by MooersLab** [schrodinger/pymol-open-source#154]
I have Anaconda3 installed, and I move my old paths out of the way to provide a clean install.
I followed the suggestion found [here](https://pymolwiki.org/index.php/CCTBX) for Mac OS X.
I am using 10.15.7.
I have a pymol license.

```bash
conda create -n env1 schrodinger::pymol conda-forge::cctbx-base schrodinger::tk
```
The install goes without error messages.

Then 
```python
❯ conda activate env1
❯ python
Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:50:20)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymol import cmd
PyMOL failed to start, dumping diagnostics...
pymol-2.4.1-py38hbb5393a_0.json
conda build: py38hbb5393a_0 https://conda.anaconda.org/schrodinger/osx-64

Operating System:
macOS-10.15.7-x86_64-i386-64bit
PyQt5 5.12.3 (Qt 5.12.9)

Python:
3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:50:20)
[Clang 11.0.0 ]
prefix=/opt/anaconda/envs/env1
executable=/opt/anaconda/envs/env1/bin/python
filesystemencoding=utf-8

Qt, Python and PyMOL Environment Variables:
LANG=en_US.UTF-8
PYMOL_DATA=/opt/anaconda/envs/env1/share/pymol/data
PYMOL_PATH=/opt/anaconda/envs/env1/share/pymol
QT_API=pyqt5
QT_XKB_CONFIG_ROOT=/opt/anaconda/envs/env1/lib

PATH:
/opt/anaconda/envs/env1/bin:/opt/anaconda/bin:/Users/blaine/.opam/default/bin:
/usr/local/gromacs/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local
/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/anaconda/condabin

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/env1/lib/python3.8/site-packages/pymol/__init__.py", line 649, in <module>
    import pymol._cmd
ImportError: dlopen(/opt/anaconda/envs/env1/lib/python3.8/site-packages/pymol/_cmd.cpython-38-darwin.so, 2): Symbol not found: ___CFConstantStringClassReference
  Referenced from: /opt/anaconda/envs/env1/lib/python3.8/site-packages/pymol/_cmd.cpython-38-darwin.so
  Expected in: flat namespace
 in /opt/anaconda/envs/env1/lib/python3.8/site-packages/pymol/_cmd.cpython-38-darwin.so
>>> exit()
```

I tried installing with a python3.7 interpreter (the default above was 3.8.6) and using pymol-bundle.
Same result.

```bash
conda create -n env3 schrodinger::pymol-bundle conda-forge::cctbx-base schrodinger::tk python=3.7

❯ python -c 'from pymol import pymol'
PyMOL failed to start, dumping diagnostics...
pymol-web-examples-2.4-1.json
conda build: 1 https://conda.anaconda.org/schrodinger/noarch
pymol-bundle-2.4.1-0.json
conda build: 0 https://conda.anaconda.org/schrodinger/osx-64
pymol-2.4.1-py37h92f0605_0.json
conda build: py37h92f0605_0 https://conda.anaconda.org/schrodinger/osx-64

Operating System:
Darwin-19.6.0-x86_64-i386-64bit
PyQt5 5.12.3 (Qt 5.12.9)

Python:
3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 20:58:55)
[Clang 11.0.0 ]
prefix=/opt/anaconda/envs/env3
executable=/opt/anaconda/envs/env3/bin/python
filesystemencoding=utf-8

Qt, Python and PyMOL Environment Variables:
LANG=en_US.UTF-8
PYMOL_DATA=/opt/anaconda/envs/env3/share/pymol/data
PYMOL_PATH=/opt/anaconda/envs/env3/share/pymol
QT_API=pyqt5
QT_XKB_CONFIG_ROOT=/opt/anaconda/envs/env3/lib

PATH:
/opt/anaconda/envs/env3/bin:/opt/anaconda/bin:/Users/blaine/.opam/default/bin:
/usr/local/gromacs/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local
/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/anaconda/condabin

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda/envs/env3/lib/python3.7/site-packages/pymol/__init__.py", line 649, in <module>
    import pymol._cmd
ImportError: dlopen(/opt/anaconda/envs/env3/lib/python3.7/site-packages/pymol/_cmd.cpython-37m-darwin.so, 2): Symbol not found: ___CFConstantStringClassReference
  Referenced from: /opt/anaconda/envs/env3/lib/python3.7/site-packages/pymol/_cmd.cpython-37m-darwin.so
  Expected in: flat namespace
 in /opt/anaconda/envs/env3/lib/python3.7/site-packages/pymol/_cmd.cpython-37m-darwin.so
```

**Comment by MooersLab** [comment]
I closed the issue by accident.

**Comment by speleo3** [comment]
Thanks @MooersLab for the bug report. We're working on a fix, shouldn't take too long.

In the meantime, please try this workaround:
```bash
conda install schrodinger::glew
```

**Comment by speleo3** [comment]
We've pushed a new build to anaconda cloud (pymol-2.4.2), this should fix the issue.
