### ISSUE TITLE
"cmd" name is taken in another standard library

### ISSUE THREAD

**Issue by bionicles** [schrodinger/pymol-open-source#18]
PyMol "CMD" conflicts with default Python CMD library used by a dependency of SpaCy NLP:
AI projects might run into this issue...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXXXXXXXXXXXXXXXXX/src/__init__.py", line 3, in <module>
    from src.tasks.stories.stories import StoriesEnv
  File "XXXXXXXXXXXXXXXXXX/src/tasks/stories/stories.py", line 11, in <module>
    import spacy  # don't forget to python -m spacy download en
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/spacy/__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/spacy/cli/download.py", line 4, in <module>
    import plac
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/plac.py", line 35, in <module>
    from plac_ext import (Interpreter, import_main, ReadlineInput, 
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/plac_ext.py", line 10, in <module>
    import cmd
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "/home/bion/anaconda3/envs/tfg/lib/python3.6/site-packages/pymol/__init__.py", line 641, in find_spec
    raise CmdException(msg)
pymol.CmdException:  Error: use "from pymol import cmd" instead of "import cmd"

**Comment by bionicles** [comment]
Hi, I was able to fix this problem myself by changing my  src/__init__.py file to place the import of StoriesEnv above the import of the PyMolEnv (both openai gym envs, one for nlp one for molecules)
