### ISSUE TITLE
scene_panel_menu_dialog not available in Tcl/Tk GUI

### ISSUE THREAD

**Issue by cgohlke** [schrodinger/pymol-open-source#189]
Pymol 2.6.0a0 fails to start when using the pmg_tk GUI backend, e.g.

```Python traceback
Traceback (most recent call last):
  File "X:\pypy3\site-packages\pmg_tk\__init__.py", line 30, in run
    PMGApp(pymol_instance,skin).run(poll)
  File "X:\pypy3\site-packages\pmg_tk\PMGApp.py", line 369, in __init__
    self.runSkin()
  File "X:\pypy3\site-packages\pmg_tk\PMGApp.py", line 289, in runSkin
    self.skin.setup()
  File "X:\pypy3\site-packages\pmg_tk\skins\normal\__init__.py", line 1254, in setup
    self.createInterface()
  File "X:\pypy3\site-packages\pmg_tk\skins\normal\__init__.py", line 1229, in createInterface
    self.createMenuBar()
  File "X:\pypy3\site-packages\pmg_tk\skins\normal\__init__.py", line 1069, in createMenuBar
    for _, label, data in self.get_menudata():
  File "X:\pypy3\site-packages\pymol\_gui.py", line 776, in get_menudata
    ('command', 'Scenes...', self.scene_panel_menu_dialog),
AttributeError: 'Normal' object has no attribute 'scene_panel_menu_dialog'
```

Workaround:
```diff
--- a/modules/pmg_tk/skins/normal/__init__.py
+++ b/modules/pmg_tk/skins/normal/__init__.py
@@ -98,7 +98,10 @@ class Normal(PMGSkin, pymol._gui.PyMOLDesktopGUI):
                       'All rights reserved.')
     contactweb     = 'http://www.pymol.org'
     contactemail   = 'sales@schrodinger.com'
-
+
+    def scene_panel_menu_dialog(self):
+        print("scene_panel_menu_dialog not available in pmg_tk.")
+
     # responsible for setup and takedown of the normal skin

     def _inc_fontsize(self, delta, font):
```

**Comment by JarrettSJohnson** [comment]
Thanks Christoph! If you'd like, feel free to submit a PR if it's convenient and I'll quickly merge. Otherwise, we'll fix this first thing on Monday.
