### ISSUE TITLE
PyMOL traceback error when building residues

### ISSUE THREAD

**Issue by mtelia** [schrodinger/pymol-open-source#253]
Hi, I'm a student using pymol for a biochemistry course and have been having some recent issues with the program. When I attempt to build a residue by navigating to the "build" dropdown from my top navigation bar then selecting a residue from the given list, I get this error: 

Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/_gui.py", line 193, in <lambda>
    ('command', lab, lambda v=val: cmd.editor.attach_amino_acid('pk1', v))
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/editor.py", line 108, in attach_amino_acid
    bound_count = _self.count_atoms("bound_to " + selection)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/querying.py", line 1460, in count_atoms
    r = _cmd.select(_self._COb,"_count_tmp","("+str(selection)+")",1,int(state)-1,str(domain))
pymol.CmdException:  Error: Invalid selection name "pk1".
( bound_to pk1 )<--
Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/_gui.py", line 193, in <lambda>
    ('command', lab, lambda v=val: cmd.editor.attach_amino_acid('pk1', v))
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/editor.py", line 108, in attach_amino_acid
    bound_count = _self.count_atoms("bound_to " + selection)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/querying.py", line 1460, in count_atoms
    r = _cmd.select(_self._COb,"_count_tmp","("+str(selection)+")",1,int(state)-1,str(domain))
pymol.CmdException:  Error: Invalid selection name "pk1".
( bound_to pk1 )<--

How do I fix this? I've tried deleting all pymol files and re-downloading the software in case some files were lost but that did not resolve it. Any help would be appreciated!

**Comment by Kheartz** [comment]
Hello!

I believe this is a duplicate of https://github.com/schrodinger/pymol-open-source/issues/252

I tend to close these issues since this affects only Edu/Incentive versions of PyMOL and not open source. We plan to have this fixed for the next maintenance release next week Wednesday. In the meantime, have you tried using the `Builder` panel to see if that worked?

**Comment by JarrettSJohnson** [comment]
Hello!

I believe this is a duplicate of https://github.com/schrodinger/pymol-open-source/issues/252

I tend to close these issues since this affects only Edu/Incentive versions of PyMOL and not open source. We plan to have this fixed for the next maintenance release next week Wednesday. In the meantime, have you tried using the Builder panel to see if that worked?
