### ISSUE TITLE
setup.py ignoring library search  environment variables.

### ISSUE THREAD

**Issue by ErikPoppleton** [schrodinger/pymol-open-source#287]
In the installation instructions it says:

> Environment variables:
> PREFIX_PATH   Colon-delimited list of paths to search for headers and
>                     libraries, e.g. $HOME/mmtf-cpp:$HOME/msgpack-c:/opt/local
> CXX           C++ compiler command
> CC            C compiler command
> CXXFLAGS      C++ compiler flags
> CFLAGS        C compiler and linker flags
> CPPFLAGS      C/C++ preprocessor flags, e.g. -I/tmp/msgpack-c/include
> LDFLAGS       linker flags

I have many of the libraries required in `$HOME/.local/include` due to not having admin privileges on my computer.  So I set:
```bash
PREFIX_PATH=/Users/erikpoppleton/.local/include:/Users/erikpoppleton/.local/lib
CFLAGS=-I/Users/erikpoppleton/.local/include
CXXFLAGS=-I/Users/erikpoppleton/.local/include
```
In addition to having this directory on my $PATH itself.
 
However pymol's setup.py completely ignores these when I try to run it and I get a bunch of `'X.h' file not found` errors.
```
contrib/uiuc/plugins/molfile_plugin/src/netcdfplugin.c:27:10: fatal error: 'netcdf.h' file not found
layer0/os_gl.h:23:10: fatal error: 'GL/glew.h' file not found
layer1/Ray.h:22:10: fatal error: 'glm/glm.hpp' file not found
```

Despite these files being in the directory specified in the environment variables:  
```
% find ~/.local  \( -name netcdf.h -o -name glew.h -o -name glm.hpp \) 
/Users/erikpoppleton/.local/include/GL/glew.h
/Users/erikpoppleton/.local/include/netcdf.h
/Users/erikpoppleton/.local/include/glm/glm.hpp
```

Same problem with linking the actual libraries which are in ~/.local/lib/ if I move the header files into the directory which wants them.

This is on MacOS 13.0.1 and an up-to-date pull from the master branch of this repository.

**Comment by speleo3** [comment]
Have you tried `PREFIX_PATH=$HOME/.local`?

**Comment by ErikPoppleton** [comment]
It then finds it during installation, but the libraries cannot be loaded at runtime without relinking.

```
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.11/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "$HOME/.local/lib/python3.11/site-packages/pymol/__init__.py", line 558, in <module>
    import pymol._cmd
ImportError: dlopen($HOME/.local/lib/python3.11/site-packages/pymol/_cmd.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libGLEW.2.2.dylib
```

It then works if I run the `install_name_tool` commands I listed in my earlier post.

**Comment by JarrettSJohnson** [comment]
By chance can you post or attach a full build log? There should be a line that includes the full cmake command which includes all paths, defs, libdirs, etc...

**Comment by ErikPoppleton** [comment]
What I ended up doing was symlinking the header files PyMol needed from my .local/include directory into miniconda3/include since I noticed that was making it into the `-I...` commands that cmake was generating.  But here's the cmake commands from the build log:

```
/Users/erikpoppleton/miniconda3/lib/python3.12/site-packages/setuptools/dist.py:292: InformationOnly: Normalizing '3.2.0a' to '3.2.0a0'
  self.metadata.version = self._normalize_version(self.metadata.version)
running build_ext
cmake /Users/erikpoppleton/software/pymol-open-source -DTARGET_NAME=_cmd -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/erikpoppleton/software/pymol-open-source/build/lib.macosx-11.1-arm64-cpython-312/pymol -DCMAKE_BUILD_TYPE=Release -DALL_INC_DIR=include;contrib/uiuc/plugins/include;ov/src;layer0;layer1;layer2;layer3;layer4;layer5;build/generated;contrib/uiuc/plugins/molfile_plugin/src;/Users/erikpoppleton/miniconda3/lib/python3.12/site-packages/numpy/_core/include;/Users/erikpoppleton/miniconda3/include;/Users/erikpoppleton/miniconda3/include/freetype2;/Users/erikpoppleton/miniconda3/include/libxml2;/Users/erikpoppleton/miniconda3/include/python3.12;/Users/erikpoppleton/miniconda3/include/python3.12; -DALL_SRC=build/generated/ShaderText.cpp;contrib/uiuc/plugins/molfile_plugin/src/PlugIOManagerInit.c;contrib/uiuc/plugins/molfile_plugin/src/abinitplugin.c;contrib/uiuc/plugins/molfile_plugin/src/avsplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/basissetplugin.c;contrib/uiuc/plugins/molfile_plugin/src/bgfplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/binposplugin.c;contrib/uiuc/plugins/molfile_plugin/src/biomoccaplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/brixplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/carplugin.c;contrib/uiuc/plugins/molfile_plugin/src/ccp4plugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/corplugin.c;contrib/uiuc/plugins/molfile_plugin/src/crdplugin.c;contrib/uiuc/plugins/molfile_plugin/src/cubeplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/dcdplugin.c;contrib/uiuc/plugins/molfile_plugin/src/dlpolyplugin.c;contrib/uiuc/plugins/molfile_plugin/src/dsn6plugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/dtrplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/dxplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/edmplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/fs4plugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/gamessplugin.c;contrib/uiuc/plugins/molfile_plugin/src/graspplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/grdplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/gridplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/gromacsplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/hash.c;contrib/uiuc/plugins/molfile_plugin/src/inthash.c;contrib/uiuc/plugins/molfile_plugin/src/jsplugin.c;contrib/uiuc/plugins/molfile_plugin/src/maeffplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/mapplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/mdfplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/mol2plugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/moldenplugin.c;contrib/uiuc/plugins/molfile_plugin/src/molemeshplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/msmsplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/namdbinplugin.c;contrib/uiuc/plugins/molfile_plugin/src/netcdfplugin.c;contrib/uiuc/plugins/molfile_plugin/src/offplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/parm7plugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/parmplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/pbeqplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/pdbplugin.c;contrib/uiuc/plugins/molfile_plugin/src/pdbxplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/phiplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/pltplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/plyplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/pqrplugin.c;contrib/uiuc/plugins/molfile_plugin/src/psfplugin.c;contrib/uiuc/plugins/molfile_plugin/src/raster3dplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/rst7plugin.c;contrib/uiuc/plugins/molfile_plugin/src/situsplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/spiderplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/stlplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/tinkerplugin.c;contrib/uiuc/plugins/molfile_plugin/src/uhbdplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/vasp5xdatcarplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vaspchgcarplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vaspoutcarplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vaspparchgplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vaspposcarplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vaspxdatcarplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vaspxmlplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vtfplugin.c;contrib/uiuc/plugins/molfile_plugin/src/vtkplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/xbgfplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/xsfplugin.cpp;contrib/uiuc/plugins/molfile_plugin/src/xyzplugin.c;layer0/Bezier.cpp;layer0/Block.cpp;layer0/CarveHelper.cpp;layer0/ContourSurf.cpp;layer0/Crystal.cpp;layer0/Err.cpp;layer0/Feedback.cpp;layer0/Field.cpp;layer0/File.cpp;layer0/GFXManager.cpp;layer0/GenericBuffer.cpp;layer0/GraphicsUtil.cpp;layer0/Isosurf.cpp;layer0/Map.cpp;layer0/Match.cpp;layer0/Matrix.cpp;layer0/MemoryDebug.cpp;layer0/MemoryUsage.cpp;layer0/MyPNG.cpp;layer0/Parse.cpp;layer0/Pixmap.cpp;layer0/PostProcess.cpp;layer0/PrintUtils.cpp;layer0/ShaderMgr.cpp;layer0/ShaderPreprocessor.cpp;layer0/ShaderPrg.cpp;layer0/Sphere.cpp;layer0/TTT.cpp;layer0/Tetsurf.cpp;layer0/Texture.cpp;layer0/Tracker.cpp;layer0/Triangle.cpp;layer0/Util.cpp;layer0/Util2.cpp;layer0/Vector.cpp;layer0/Word.cpp;layer0/ccealignmodule.cpp;layer0/marching_cubes.cpp;layer0/os_gl.cpp;layer1/Basis.cpp;layer1/ButMode.cpp;layer1/CGO.cpp;layer1/CGOGL.cpp;layer1/CGORenderer.cpp;layer1/COLLADA.cpp;layer1/Camera.cpp;layer1/Character.cpp;layer1/Color.cpp;layer1/Control.cpp;layer1/Extrude.cpp;layer1/Font.cpp;layer1/FontGLUT.cpp;layer1/FontGLUT8x13.cpp;layer1/FontGLUT9x15.cpp;layer1/FontGLUTHel10.cpp;layer1/FontGLUTHel12.cpp;layer1/FontGLUTHel18.cpp;layer1/FontType.cpp;layer1/ImageUtils.cpp;layer1/Movie.cpp;layer1/Ortho.cpp;layer1/P.cpp;layer1/PConv.cpp;layer1/Picking.cpp;layer1/Pop.cpp;layer1/PyMOLObject.cpp;layer1/Ray.cpp;layer1/Rep.cpp;layer1/Scene.cpp;layer1/SceneMouse.cpp;layer1/ScenePicking.cpp;layer1/SceneRay.cpp;layer1/SceneRender.cpp;layer1/SceneView.cpp;layer1/ScrollBar.cpp;layer1/Seq.cpp;layer1/Setting.cpp;layer1/Shaker.cpp;layer1/SymOp.cpp;layer1/SymOpPConv.cpp;layer1/SymOpTools.cpp;layer1/Symmetry.cpp;layer1/Text.cpp;layer1/TypeFace.cpp;layer1/View.cpp;layer1/Wizard.cpp;layer2/AssemblyHelpers.cpp;layer2/AtomInfo.cpp;layer2/AtomInfoHistory.cpp;layer2/BondTypeHistory.cpp;layer2/CifFile.cpp;layer2/CifMoleculeReader.cpp;layer2/CoordSet.cpp;layer2/DistSet.cpp;layer2/GadgetSet.cpp;layer2/HydrogenAdder.cpp;layer2/MmodTyping.cpp;layer2/MmtfMoleculeReader.cpp;layer2/Mol2Typing.cpp;layer2/MolV3000.cpp;layer2/ObjectAlignment.cpp;layer2/ObjectCGO.cpp;layer2/ObjectCallback.cpp;layer2/ObjectCurve.cpp;layer2/ObjectDist.cpp;layer2/ObjectGadget.cpp;layer2/ObjectGadgetRamp.cpp;layer2/ObjectGroup.cpp;layer2/ObjectMap.cpp;layer2/ObjectMesh.cpp;layer2/ObjectMolecule.cpp;layer2/ObjectMolecule2.cpp;layer2/ObjectMolecule3.cpp;layer2/ObjectSlice.cpp;layer2/ObjectSurface.cpp;layer2/ObjectVolume.cpp;layer2/RepAngle.cpp;layer2/RepCartoon.cpp;layer2/RepCylBond.cpp;layer2/RepDihedral.cpp;layer2/RepDistDash.cpp;layer2/RepDistLabel.cpp;layer2/RepDot.cpp;layer2/RepEllipsoid.cpp;layer2/RepLabel.cpp;layer2/RepMesh.cpp;layer2/RepNonbonded.cpp;layer2/RepNonbondedSphere.cpp;layer2/RepRibbon.cpp;layer2/RepSphere.cpp;layer2/RepSphereGenerate.cpp;layer2/RepSphereImmediate.cpp;layer2/RepSurface.cpp;layer2/RepWireBond.cpp;layer2/Sculpt.cpp;layer2/SculptCache.cpp;layer2/SideChainHelper.cpp;layer2/VFont.cpp;layer3/AtomIterators.cpp;layer3/CifDataValueFormatter.cpp;layer3/Editor.cpp;layer3/Executive.cpp;layer3/ExecutivePython.cpp;layer3/Interactions.cpp;layer3/MaeExportHelpers.cpp;layer3/MoleculeExporter.cpp;layer3/MovieScene.cpp;layer3/PlugIOManager.cpp;layer3/RingFinder.cpp;layer3/Seeker.cpp;layer3/Selector.cpp;layer3/SelectorTmp.cpp;layer3/SpecRec.cpp;layer3/SpecRecSpecial.cpp;layer4/Cmd.cpp;layer4/Menu.cpp;layer4/PopUp.cpp;layer5/PyMOL.cpp;layer5/TestPyMOL.cpp;layer5/main.cpp;ov/src/OVContext.cpp;ov/src/OVHeap.cpp;ov/src/OVHeapArray.cpp;ov/src/OVLexicon.cpp;ov/src/OVOneToAny.cpp;ov/src/OVOneToOne.cpp;ov/src/OVRandom.cpp;ov/src/ov_utility.cpp; -DALL_DEF=_PYMOL_LIBPNG;_PYMOL_FREETYPE;_PYMOL_VMD_PLUGINS;_HAVE_LIBXML;_PYMOL_NO_MSGPACKC;_PYMOL_NO_MAIN;PYMOL_CURVE_VALIDATE;_PYMOL_OSX;_PYMOL_NUMPY; -DALL_LIB_DIR=/Users/erikpoppleton/miniconda3/lib;/usr/lib; -DALL_LIB=png;freetype;xml2;GLEW;netcdf; -DALL_COMP_ARGS=-Werror=return-type;-Wunused-variable;-Wno-switch;-Wno-narrowing;-Wno-char-subscripts;-O3;-fno-strict-aliasing; "-DALL_EXT_LINK=-framework OpenGL" -DSHARED_SUFFIX=.cpython-312-darwin.so
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd
cmake --build . --config Release -j8
/Users/erikpoppleton/.local/bin/cmake -S/Users/erikpoppleton/software/pymol-open-source -B/Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd --check-build-system CMakeFiles/Makefile.cmake 0
/Users/erikpoppleton/.local/bin/cmake -E cmake_progress_start /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd/CMakeFiles /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd//CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/_cmd.dir/build.make CMakeFiles/_cmd.dir/depend
cd /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd && /Users/erikpoppleton/.local/bin/cmake -E cmake_depends "Unix Makefiles" /Users/erikpoppleton/software/pymol-open-source /Users/erikpoppleton/software/pymol-open-source /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd /Users/erikpoppleton/software/pymol-open-source/build/temp.macosx-11.1-arm64-cpython-312/_cmd/CMakeFiles/_cmd.dir/DependInfo.cmake "--color="
```

The `-DALL_INC_DIR` appears to be missing `.local/include`

**Comment by JarrettSJohnson** [comment]
Thanks, Erik. One more thing. In the `setup.py`, there is this block
```python
for prefix in prefix_path:
    for dirs, suffixes in [
        [
            inc_dirs,
            [
                ("include",),
                ("include", "freetype2"),
                ("include", "libxml2"),
                ("include", "openvr"),
            ],
        ],
        [lib_dirs, [("lib64",), ("lib",)]],
    ]:
        dirs.extend(filter(os.path.isdir, [os.path.join(prefix, *s) for s in suffixes]))
```

can we just confirm the paths here by replacing it with

```python
for prefix in prefix_path:
    print(f"PREFIX: {prefix}")
    print(f"PRE: {inc_dirs}")
    for dirs, suffixes in [
        [
            inc_dirs,
            [
                ("include",),
                ("include", "freetype2"),
                ("include", "libxml2"),
                ("include", "openvr"),
            ],
        ],
        [lib_dirs, [("lib64",), ("lib",)]],
    ]:
        dirs.extend(filter(os.path.isdir, [os.path.join(prefix, *s) for s in suffixes]))
    print("-------------")
    print(f"POST: {inc_dirs}")
    exit(1)
```
This will prevent the build from happening but print out the before and after include directories. Curious to see what the transformation of the include directory looks like.

**Comment by JarrettSJohnson** [comment]
Yep, that'll do it!
