### ISSUE TITLE
Pymol portable not opening on Windows 10

### ISSUE THREAD

**Issue by saurabhgayali** [schrodinger/pymol-open-source#40]
I am running pymol portable v2.3.0_66 in Windows 10
It never opened and below is the ouput when ran with +2 arguments.

```
E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL>PyMOLWin.exe +2Traceback (most recent call last):

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\runpy.py", line 193, in _run_module_as_main

"__main__", mod_spec)

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\runpy.py", line 85, in _run_code

exec(code, run_globals)

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\site-packages\pymol\__main__.py", line 10, in <module>

pymol.launch()

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\site-packages\pymol\__init__.py", line 483, in launch

from pmg_qt import pymol_qt_gui

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\site-packages\pmg_qt\pymol_qt_gui.py", line 17, in <module>

from pymol.Qt import QtGui, QtCore, QtWidgets

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\site-packages\pymol\Qt\__init__.py", line 15, in <module>

from pymol._Qt_pre import *

File "E:\Downloads\PyMOL-2.3.0_66-Win64-portable-py37\PyMOL\lib\site-packages\pymol\_Qt_pre.py", line 2, in <module>

from PyQt5 import QtGui, QtCore, QtOpenGL

ImportError: DLL load failed: The specified procedure could not be found.   
```

**Comment by speleo3** [comment]
Can you try the very latest build?
https://pymol.org/installers/PyMOL-2.3.2_81-Win64-portable-py37.zip
It will dump some diagnostics data on DLL import failure.

**Comment by YoavShamir5** [comment]
Hi, I am getting the same error having installed Pymol along with Python 3.7. 
I already have Python 3.8 installed, where importing PyQt5 works just fine. 

Would appreciate your help with this, thanks!

**Comment by saurabhgayali** [comment]
> Can you try the very latest build? https://pymol.org/installers/PyMOL-2.3.2_81-Win64-portable-py37.zip It will dump some diagnostics data on DLL import failure.

This one is working now.
