### ISSUE TITLE
Error: no prior image available when export image

### ISSUE THREAD

**Issue by JiahaoWongg** [schrodinger/pymol-open-source#412]
When adding labels for hydrogen bonds and amino acid residues, the image export failed. However, there were no errors before adding them. The specific error message is as follows:

```sh
Traceback (most recent call last):
  File "C:\software\PyMOL2\lib\site-packages\pmg_qt\pymol_qt_gui.py", line 1078, in run_save
    self.cmd.png(fname, prior=1, dpi=form.input_dpi.currentText())
  File "C:\software\PyMOL2\lib\site-packages\pymol\exporting.py", line 619, in png
    raise pymol.CmdException("no prior image available")
pymol.CmdException:  Error: no prior image available
```
Thanks!

**Comment by JarrettSJohnson** [comment]
Thanks. For now, I'd probably try using the `png` command manually without supplying `prior` arg.
