### ISSUE TITLE
Pdb file load fail

### ISSUE THREAD

**Issue by gj218** [schrodinger/pymol-open-source#48]
Trying to load a pdb file on a Fedora Core 30 system produces the following traceback:

```
Traceback (most recent call last):
  File "/xsoft/pymol-open-source/modules/pmg_qt/pymol_qt_gui.py", line 626, in file_open
    if not self.load_dialog(fname, partial=partial):
  File "/xsoft/pymol-open-source/modules/pmg_qt/file_dialogs.py", line 24, in load_dialog
    parent.initialdir = os.path.dirname(fname)
  File "/usr/lib64/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'QString' object has no attribute 'rfind'
```

**Comment by speleo3** [comment]
Is this using Qt4? We don't use the `QString` API, sounds like something's going wrong here:

https://github.com/schrodinger/pymol-open-source/blob/67248b9120fd36b7714af50218dfb89ea54c5035/modules/pymol/Qt/__init__.py#L42
