### ISSUE TITLE
Unable to run PyMol on Windows 10 - build from source

### ISSUE THREAD

**Issue by eusebiu** [schrodinger/pymol-open-source#60]
I am trying to build PyMol from source and after build I get this error when running it.

I only used Win32 libs (freeglut, freetype, glew32, libpng, msgpack) and the build was successful.

C:\PyMol\Scripts>pymol.bat
C:\PyMol\Scripts>"C:\PyMol\Scripts\\..\..\Python37-32\python.exe" "C:\PyMol\Scripts\\..\Lib\site-packages\pymol\__init__.py"
Traceback (most recent call last):
  File "C:\PyMol\Scripts\\..\Lib\site-packages\pymol\__init__.py", line 64, in <module>
    import pymol
  File "C:\PyMol\Lib\site-packages\pymol\__init__.py", line 562, in <module>
    import pymol._cmd
ImportError: DLL load failed: %1 is not a valid Win32 application.

Line 562 is:
import pymol._cmd
_cmd = sys.modules['pymol._cmd']

Any ideas what is the issue? How can I configure the setup.py to build in x64?

**Comment by speleo3** [comment]
This could happen for example if you have an incompatible `C:\Windows\System32\zlib.dll`

**Comment by eusebiu** [comment]
I got the one from zlib-msvc14-x86.1.2.11.7795 and still no luck.

**Comment by speleo3** [comment]
Does the bundle from https://pymol.org/#download work? Download the ZIP, unpack, and run `PyMOLWin.exe` (or `PyMOLWinWithConsole.bat`)

**Comment by eusebiu** [comment]
Yes, it does.
I was also able to install & run the precompiled version of PyMol (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pymol) with no issues.

**Comment by cgohlke** [comment]
> ImportError: DLL load failed: %1 is not a valid Win32 application.

Try to open `pymol/_cmd.cp37-win32.pyd` using [Dependencies](https://github.com/lucasg/Dependencies/releases) and check for missing or conflicting DLLs.

**Comment by eusebiu** [comment]
All dependecies are there and now I get:
C:\PyMol\Scripts>pymol.bat

C:\PyMol\Scripts>"C:\PyMol\Scripts\\..\..\Python38-32\python.exe" "C:\PyMol\Scripts\\..\Lib\site-packages\pymol\__init__.py"
Traceback (most recent call last):
  File "C:\PyMol\Scripts\\..\Lib\site-packages\pymol\__init__.py", line 64, in <module>
    import pymol
  File "C:\PyMol\Lib\site-packages\pymol\__init__.py", line 562, in <module>
    import pymol._cmd
ImportError: DLL load failed while importing _cmd: The specified module could not be found.

**Comment by baodongning** [comment]
do u fix this , i have same problem

**Comment by baodongning** [comment]
do u fix this?

**Comment by Liuyangying** [comment]
I also meet this issue, how do you fix it?
